before_script:
  - npm install truffle-hdwallet-provider-privkey
  - npm install dotenv
  - npm install -g truffle
  - npm install -g ganache-cli

script:
- ganache-cli -p 8545 > /dev/null &
- sleep 5
- truffle migrate 
- truffle test

notifications:
  slack: affogatonetwork:WKER9ofwwM1n1TsMJHL9QXnm