FROM node
COPY . /core


# Clone and install wait-for-it
RUN git clone https://github.com/vishnubob/wait-for-it \
    && cp wait-for-it/wait-for-it.sh /usr/local/bin \
    && chmod +x /usr/local/bin/wait-for-it.sh 



# Set working directory

WORKDIR /core
ENV ganache_host ""
RUN npm install -g truffle --unsafe-perm
RUN truffle compile
CMD wait-for-it.sh $ganache_host:8545 -t 30 && truffle migrate --network docker